import { GfycatData } from "./GfycatData";
import { NadeMovement } from "./NadeMovement";
import { Tickrate } from "./NadeTickrate";
import { NadeType } from "./NadeType";
import { Technique } from "./Technique";
import { CsMap } from "../../map/models/CsGoMap";
import { TeamSide } from "./TeamSide";
import { GameMode } from "./GameMode";
import { CsCanvasCoordinate } from "./MapCoordinates";

export type NadeCreateBody = {
  description: string;
  endPosition: string;
  gameMode: GameMode;
  gfycat?: GfycatData;
  imageBase64: string;
  isPro?: boolean;
  lineUpImageBase64?: string;
  map: CsMap;
  mapEndCoord: CsCanvasCoordinate;
  mapStartCoord: CsCanvasCoordinate;
  movement: NadeMovement;
  oneWay?: boolean;
  proUrl?: string;
  setPos?: string;
  startPosition: string;
  teamSide?: TeamSide;
  technique: Technique;
  tickrate?: Tickrate;
  type: NadeType;
  youTubeId?: string;
};
