import { UserLight } from "../../users/models/User";
import { GfycatData } from "./GfycatData";
import { NadeMovement } from "./NadeMovement";
import { Tickrate } from "./NadeTickrate";
import { NadeType } from "./NadeType";
import { Technique } from "./Technique";
import { NadeStatus } from "./Status";
import { CsgoMap } from "../../map/models/CsGoMap";
import { TeamSide } from "./TeamSide";
import { GameMode } from "./GameMode";
import { MapCoordinates } from "./MapCoordinates";
import { NadeImages } from "./NadeImages";

export interface NadeLight {
  commentCount: number;
  createdAt: Date | string;
  eloScore: number;
  endPosition?: string;
  favoriteCount: number;
  gameMode: GameMode;
  gfycat?: GfycatData;
  id: string;
  images: NadeImages;
  isFavorited?: boolean;
  isNew?: boolean;
  isPro?: boolean;
  map?: CsgoMap;
  mapEndCoord?: MapCoordinates;
  movement?: NadeMovement;
  oneWay?: boolean;
  proUrl?: string;
  score: number;
  slug?: string;
  startPosition?: string;
  status: NadeStatus;
  teamSide?: TeamSide;
  technique?: Technique;
  tickrate?: Tickrate;
  type?: NadeType;
  user: UserLight;
  viewCount: number;
  youTubeId?: string;
}
